version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=voting-db-user
      - POSTGRES_PASSWORD=voting
      - POSTGRES_DB=votingdb
    ports:
      - "5437:5432"
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge
