spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5437/votingdb
spring.datasource.username=voting-db-user
spring.datasource.password=voting
spring.liquibase.change-log=db.changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true